#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

title: BBC BUG
description: Broadcast Universal Gateway
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: bug
show_downloads: true

footer_content: >
    BUG was created at the <a href='https://bbc.co.uk/'>BBC</a>, 
    by <a href='https://github.com/geoffhouse'>Geoff House</a> and 
    <a href='https://github.com/ryanmccartney'>Ryan McCartney</a>.
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
    "BUG on GitHub":
        - "//github.com/bbc/bug"

nav_external_links:
    - title: Component Library
      url: /storybook/

sidebar: _data/sidebar.yml
